from cv2.typing import MatLike


class VideoStreamingServer:
	def __init__(self, host: str = "localhost", port: int = 8080) -> None: ...

	def add_stream(self, stream_id: str) -> None: ...

	def update_stream(self, stream_id: str, frame: MatLike) -> None: ...

	def start(self) -> None: ...

	def stop(self) -> None: ...
